name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main  # ou outro branch que você deseja usar

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Passo 2: Logar no Docker Hub
      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Passo 3: Configurar o Docker Buildx para builds multi-plataforma
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Passo 4: Build e Push da imagem Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-app:latest
          
      # Passo 5: Limpar cache Docker
      - name: Docker logout
        run: docker logout
